Fix cross compiling sparc64 on arm32 host
Add arm32 to the whitelist for handling lack of int128 type variants.
Otherwise we get errors like:

/target/include/asm/types.h:79:1: error: unknown type name ‘__int128_t’
    typedef __int128_t dcell;

This may introduce issues building on aarch64 but I have no way to test.

Signed-off-by: Cole Robinson <crobinso@redhat.com>
Signed-off-by: Mark Cave-Ayland <mark.cave-ayland@ilande.co.uk>

git-svn-id: svn://openbios.org/openbios/trunk/openbios-devel@1239 f158a5a8-5612-0410-a976-696ce0be7e32